### YamlMime:ModuleUnit
uid: learn.pillars-of-a-great-azure-architecture.3-design-for-security
title: セキュリティ向けの設計
metadata:
  title: セキュリティ向けの設計
  description: セキュリティ向けの設計
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 1b55aacd394eb8f956c0b0ef45713cdcc57a03b0
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47134149"
durationInMinutes: 10
content: >
  [!include[](includes/3-design-for-security.md)]
quiz:
  title: 自分の知識をチェックする
  questions:
  - content: セキュリティ保護が必要な場合があるのは、次のどの種類のデータですか。
    choices:
    - content: 個人情報を含む顧客データ
      isCorrect: false
      incorrectExplanation: このデータの適切なセキュリティ保護を提供することは重要ですが、これだけが正解ではありません。
    - content: 事業運営を支える財務データ
      isCorrect: false
      incorrectExplanation: このデータの適切なセキュリティ保護を提供することは重要ですが、これだけが正解ではありません。
    - content: 知的財産権
      isCorrect: false
      incorrectExplanation: このデータの適切なセキュリティ保護を提供することは重要ですが、これだけが正解ではありません。
    - content: 上記のすべてにセキュリティ保護が必要な場合があります
      isCorrect: true
      correctExplanation: 上記のすべてが、追加のセキュリティ保護の恩恵を受ける場合があります。
  - content: 次のうち、ポリシーとアクセスの層で発生する可能性がある攻撃の例はどれですか?
    choices:
    - content: 漏洩した資格情報のインターネットへの投稿
      isCorrect: true
      correctExplanation: 資格情報の漏洩は、組織にとって大きなリスクであり、ポリシーとアクセスの層に適用されます。
    - content: SYN フラッド攻撃
      isCorrect: false
      incorrectExplanation: SYN フラッド攻撃は、一般的にネットワーク境界で発生するサービス拒否攻撃の一種です。
    - content: 資格情報の提示なしで従業員をデータセンターに誘導すること
      isCorrect: false
      incorrectExplanation: データセンターへの従業員の誘導は物理層の攻撃です。
    - content: 仮想マシンのディスクを暗号化するランサムウェア
      isCorrect: false
      incorrectExplanation: ランサムウェア攻撃は VM/コンピューティング層の攻撃です。
