### YamlMime:ModuleUnit
uid: learn.pillars-of-a-great-azure-architecture.3-design-for-security
title: セキュリティのための設計
metadata:
  title: セキュリティのための設計
  description: セキュリティのための設計
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 10
content: |
  [!include[](includes/3-design-for-security.md)]
quiz:
  title: 知識チェック - セキュリティのための設計
  questions:
    - content: セキュリティ保護が必要な場合があるのは、次のどの種類のデータですか?
      choices:
        - content: 個人情報を含む顧客データ
          isCorrect: false
          incorrectExplanation: このデータの適切なセキュリティ保護を提供することは重要ですが、これだけが正解ではありません。
        - content: 事業運営を支える財務データ
          isCorrect: false
          incorrectExplanation: このデータの適切なセキュリティ保護を提供することは重要ですが、これだけが正解ではありません。
        - content: 知的財産を含むデータ
          isCorrect: false
          incorrectExplanation: このデータの適切なセキュリティ保護を提供することは重要ですが、これだけが正解ではありません。
        - content: 上記のすべてにセキュリティ保護が必要な場合があります
          isCorrect: true
          correctExplanation: 上記のすべてが、追加のセキュリティ保護の恩恵を受ける場合があります。
    - content: 次のうち、境界層で発生する可能性がある攻撃の例はどれですか?
      choices:
        - content: 漏洩した資格情報のインターネットへの投稿
          isCorrect: false
          incorrectExplanation: 資格情報の漏洩は組織にとって巨大なリスクですが、境界層の攻撃ではありません。
        - content: SYN フラッド攻撃
          isCorrect: true
          correctExplanation: SYN フラッド攻撃は、一般的にネットワーク境界で発生するサービス拒否攻撃の一種です。
        - content: データセンターへのドア ドラフティング
          isCorrect: false
          incorrectExplanation: ドア ドラフティングは物理層の攻撃です。
        - content: 仮想マシンのディスクを暗号化するランサムウェア
          isCorrect: false
          incorrectExplanation: ランサムウェア攻撃は VM/コンピューティング層の攻撃です。