### YamlMime:ModuleUnit
uid: principles-cloud-computing.4-cloud-deployment-models
title: クラウド デプロイ モデル
metadata:
  title: クラウド デプロイ モデル
  description: クラウド デプロイ モデル
  ms.openlocfilehash: 351e3768c891f23e2f510b4142b36b2695f8207a
  ms.sourcegitcommit: b1b68b477ab39109c48f227b504a5050cae7a718
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/01/2018
  ms.locfileid: "43414592"
durationInMinutes: 10
content: '[!include[](includes/4-cloud-deployment-models.md)]'
