### YamlMime:ModuleUnit
uid: learn.create-azure-storage-account.3-choose-your-account-settings
title: <span data-ttu-id="dc7e7-101">アカウント設定を選択する</span><span class="sxs-lookup"><span data-stu-id="dc7e7-101">Choose your account settings</span></span>
metadata:
  title: <span data-ttu-id="dc7e7-102">アカウント設定を選択する</span><span class="sxs-lookup"><span data-stu-id="dc7e7-102">Choose your account settings</span></span>
  description: <span data-ttu-id="dc7e7-103">アカウント設定を選択する</span><span class="sxs-lookup"><span data-stu-id="dc7e7-103">Choose your account settings</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 86463780f25a2aa164342d6539d35ec5586984af
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47135290"
durationInMinutes: 5
content: '[!include[](includes/3-choose-your-account-settings.md)]'
