### YamlMime:ModuleUnit
uid: learn.create-azure-storage-account.3-choose-your-account-settings
title: アカウント設定を選択する
metadata:
  title: アカウント設定を選択する
  description: アカウント設定を選択する
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 78eb3c50e696cd1e6badd052fd1782d0f8b1c9fc
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44236520"
durationInMinutes: 7
content: '[!include[](includes/3-choose-your-account-settings.md)]'
