### YamlMime:ModuleUnit
uid: learn.create-azure-storage-account.3-choose-your-account-settings
title: <span data-ttu-id="a2ff5-101">アカウント設定を選択する</span><span class="sxs-lookup"><span data-stu-id="a2ff5-101">Choose your account settings</span></span>
metadata:
  title: <span data-ttu-id="a2ff5-102">アカウント設定を選択する</span><span class="sxs-lookup"><span data-stu-id="a2ff5-102">Choose your account settings</span></span>
  description: <span data-ttu-id="a2ff5-103">アカウント設定を選択する</span><span class="sxs-lookup"><span data-stu-id="a2ff5-103">Choose your account settings</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 86463780f25a2aa164342d6539d35ec5586984af
  ms.sourcegitcommit: b21a4b22de591cfa776684ba2eab9ba27248c65d
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/19/2018
  ms.locfileid: "46354079"
durationInMinutes: 5
content: '[!include[](includes/3-choose-your-account-settings.md)]'
