### YamlMime:ModuleUnit
uid: learn.scale-and-size-virtual-machines.5-exercise-create-a-scale-set-and-configure-autoscaling
title: <span data-ttu-id="cb272-101">課題 - スケール セットの作成と自動スケールの構成</span><span class="sxs-lookup"><span data-stu-id="cb272-101">Exercise - Create a scale set and configure autoscaling</span></span>
metadata:
  title: <span data-ttu-id="cb272-102">課題 - スケール セットの作成と自動スケールの構成</span><span class="sxs-lookup"><span data-stu-id="cb272-102">Exercise - Create a scale set and configure autoscaling</span></span>
  description: <span data-ttu-id="cb272-103">課題 - スケール セットの作成と自動スケールの構成</span><span class="sxs-lookup"><span data-stu-id="cb272-103">Exercise - Create a scale set and configure autoscaling</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: a0c8a51ea1f53b0ad09a2e6e1ee76cd7bbebc9a6
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47136766"
azureSandbox: true
durationInMinutes: 20
content: '[!include[](includes/5-exercise-create-a-scale-set-and-configure-autoscaling.md)]'
