### YamlMime:ModuleUnit
uid: learn.scale-and-size-virtual-machines.5-exercise-create-a-scale-set-and-configure-autoscaling
title: <span data-ttu-id="0f026-101">課題 - スケール セットの作成と自動スケールの構成</span><span class="sxs-lookup"><span data-stu-id="0f026-101">Exercise - Create a scale set and configure autoscaling</span></span>
metadata:
  title: <span data-ttu-id="0f026-102">課題 - スケール セットの作成と自動スケールの構成</span><span class="sxs-lookup"><span data-stu-id="0f026-102">Exercise - Create a scale set and configure autoscaling</span></span>
  description: <span data-ttu-id="0f026-103">課題 - スケール セットの作成と自動スケールの構成</span><span class="sxs-lookup"><span data-stu-id="0f026-103">Exercise - Create a scale set and configure autoscaling</span></span>
  ms.openlocfilehash: ca265df828582f0b74003b36a4e33b824a111290
  ms.sourcegitcommit: 4d2d6d8c52fa24ae1c5c06cf4cb3afa09d8c8363
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44255384"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-a-scale-set-and-configure-autoscaling.md)]'
