### YamlMime:ModuleUnit
uid: learn.scale-and-size-virtual-machines.5-exercise-create-a-scale-set-and-configure-autoscaling
title: 練習 - スケール セットを作成し、自動スケールの構成
metadata:
  title: 練習 - スケール セットを作成し、自動スケールの構成
  description: 練習 - スケール セットを作成し、自動スケールの構成
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 10
content: |
  [!include[](includes/5-exercise-create-a-scale-set-and-configure-autoscaling.md)]