### YamlMime:ModuleUnit
uid: learn.enable-reliable-messaging-for-big-data-applications-using-azure-event-hubs.5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub
title: <span data-ttu-id="4a38d-101">演習 - イベント ハブを経由してメッセージを送受信するアプリケーションを構成する</span><span class="sxs-lookup"><span data-stu-id="4a38d-101">Exercise - Configure applications to send or receive messages through an Event Hub</span></span>
metadata:
  title: <span data-ttu-id="4a38d-102">演習 - イベント ハブを経由してメッセージを送受信するアプリケーションを構成する</span><span class="sxs-lookup"><span data-stu-id="4a38d-102">Exercise - Configure applications to send or receive messages through an Event Hub</span></span>
  description: <span data-ttu-id="4a38d-103">イベント ハブを経由してメッセージを送受信するアプリケーションを構成する</span><span class="sxs-lookup"><span data-stu-id="4a38d-103">Configure applications to send or receive messages through an Event Hub</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: de40d61e225340c649c9efec1ac10093508b9459
  ms.sourcegitcommit: bfff31db64f2c8831293efda430f58470b5e2617
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/18/2018
  ms.locfileid: "45994777"
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub.md)]'
