### YamlMime:ModuleUnit
uid: learn.enable-reliable-messaging-for-big-data-applications-using-azure-event-hubs.5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub
title: <span data-ttu-id="ea73b-101">イベント ハブを経由してメッセージを送受信するアプリケーションを構成する</span><span class="sxs-lookup"><span data-stu-id="ea73b-101">Configure applications to send or receive messages through an Event Hub</span></span>
metadata:
  title: <span data-ttu-id="ea73b-102">イベント ハブを経由してメッセージを送受信するアプリケーションを構成する</span><span class="sxs-lookup"><span data-stu-id="ea73b-102">Configure applications to send or receive messages through an Event Hub</span></span>
  description: <span data-ttu-id="ea73b-103">イベント ハブを経由してメッセージを送受信するアプリケーションを構成する</span><span class="sxs-lookup"><span data-stu-id="ea73b-103">Configure applications to send or receive messages through an Event Hub</span></span>
  ms.openlocfilehash: 28d21d21388a71eea65893daeb7f6d2a374c8e64
  ms.sourcegitcommit: 314b617e66d461bd6bf5aa076aacdc150b773606
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "43833703"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub.md)]'
