### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal
title: <span data-ttu-id="67409-101">Azure portal を使用して Azure VM ディスク キャッシュを有効化して構成する</span><span class="sxs-lookup"><span data-stu-id="67409-101">Enable and configure Azure VM disk cache with the Azure portal</span></span>
metadata:
  title: <span data-ttu-id="67409-102">Azure portal を使用して Azure VM ディスク キャッシュを有効化して構成する</span><span class="sxs-lookup"><span data-stu-id="67409-102">Enable and configure Azure VM disk cache with the Azure portal</span></span>
  description: <span data-ttu-id="67409-103">Azure portal を使用して Azure VM ディスク キャッシュを有効化して構成する</span><span class="sxs-lookup"><span data-stu-id="67409-103">Enable and configure Azure VM disk cache with the Azure portal</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 20238bbb5638ea2e5985a7a51e5885700f64099b
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47133327"
durationInMinutes: 5
content: <span data-ttu-id="67409-104">[!include[](includes/3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal.md)</span><span class="sxs-lookup"><span data-stu-id="67409-104">[!include[](includes/3-enable-and-configure-azure-vm-disk-cache-by-using-the-azure-portal.md)</span></span>
