### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.5-manage-cache-settings-with-powershell
title: <span data-ttu-id="ed25d-101">PowerShell でキャッシュ設定を管理する</span><span class="sxs-lookup"><span data-stu-id="ed25d-101">Manage cache settings with PowerShell</span></span>
metadata:
  title: <span data-ttu-id="ed25d-102">PowerShell でキャッシュ設定を管理する</span><span class="sxs-lookup"><span data-stu-id="ed25d-102">Manage cache settings with PowerShell</span></span>
  description: <span data-ttu-id="ed25d-103">PowerShell でキャッシュ設定を管理する</span><span class="sxs-lookup"><span data-stu-id="ed25d-103">Manage cache settings with PowerShell</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: ea17e8a45285041cb084303a7c9be0546f7b1e12
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44241158"
durationInMinutes: 10
content: '[!include[](includes/5-manage-cache-settings-with-powershell.md)]'
