### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.5-manage-cache-settings-with-powershell
title: PowerShell でキャッシュ設定を管理する
metadata:
  title: PowerShell でキャッシュ設定を管理する
  description: PowerShell でキャッシュ設定を管理する
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: ea17e8a45285041cb084303a7c9be0546f7b1e12
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44241158"
durationInMinutes: 10
content: '[!include[](includes/5-manage-cache-settings-with-powershell.md)]'
