### YamlMime:ModuleUnit
uid: learn.caching-and-performance-azure-storage-and-disks.5-manage-cache-settings-with-powershell
title: PowerShell を使用したキャッシュ設定を管理します。
metadata:
  title: PowerShell を使用したキャッシュ設定を管理します。
  description: PowerShell を使用したキャッシュ設定を管理します。
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 10
content: |
  [!include[](includes/5-manage-cache-settings-with-powershell.md)]