### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.1-create-azure-iot-central-application
title: <span data-ttu-id="41f4e-101">Azure IoT Central アプリケーションを作成する</span><span class="sxs-lookup"><span data-stu-id="41f4e-101">Create an Azure IoT Central application</span></span>
metadata:
  title: <span data-ttu-id="41f4e-102">Azure IoT Central アプリケーションを作成する</span><span class="sxs-lookup"><span data-stu-id="41f4e-102">Create an Azure IoT Central application</span></span>
  description: <span data-ttu-id="41f4e-103">Azure IoT Central アプリケーションを作成する</span><span class="sxs-lookup"><span data-stu-id="41f4e-103">Create an Azure IoT Central application</span></span>
  ms.openlocfilehash: e8c698bdbf44cc17d687466702c06b59f7023806
  ms.sourcegitcommit: b97ed72bd7e3fb77b49de71e8ef35d3f70dfd636
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43795667"
durationInMinutes: 12
content: '[!include[](includes/1-create-azure-iot-central-application.md)]'
