### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.7-exercise-add-azure-storage-configuration-to-your-app
title: <span data-ttu-id="2b357-101">演習 - アプリに Azure Storage の構成を追加する</span><span class="sxs-lookup"><span data-stu-id="2b357-101">Exercise - Add Azure Storage configuration to your app</span></span>
metadata:
  title: <span data-ttu-id="2b357-102">演習 - アプリに Azure Storage の構成を追加する</span><span class="sxs-lookup"><span data-stu-id="2b357-102">Exercise - Add Azure Storage configuration to your app</span></span>
  description: <span data-ttu-id="2b357-103">演習 - アプリに Azure Storage の構成を追加する</span><span class="sxs-lookup"><span data-stu-id="2b357-103">Exercise - Add Azure Storage configuration to your app</span></span>
  ms.openlocfilehash: 81492226750978399fb2a82fb32c14b5ddefb08d
  ms.sourcegitcommit: 107578417899e44b5611917dec7bcc21d4c1582e
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 08/29/2018
  ms.locfileid: "43229299"
durationInMinutes: 10
content: '[!include[](includes/7-exercise-add-azure-storage-configuration-to-your-app.md)]'
