### YamlMime:ModuleUnit
uid: learn.connect-app-to-azure-storage.9-exercise-connect-with-your-azure-storage-configuration
title: Azure Storage の構成に接続する
metadata:
  title: Azure Storage の構成に接続する
  description: Azure Storage の構成に接続する
  ms.openlocfilehash: d751f669ef3861a64abfdd02301aa7e79edb9c12
  ms.sourcegitcommit: e90461bc6f88bca3b53183b476553633f93990a3
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "44043782"
durationInMinutes: 10
content: '[!include[](includes/9-exercise-connect-with-your-azure-storage-configuration.md)]'
