### YamlMime:ModuleUnit
uid: learn.manage-secrets-with-azure-key-vault.6-configure-deploy-run-azure
title: <span data-ttu-id="fe173-101">Azure での構成、展開、実行</span><span class="sxs-lookup"><span data-stu-id="fe173-101">Configure, deploy, and run in Azure</span></span>
metadata:
  title: <span data-ttu-id="fe173-102">Azure での構成、展開、実行</span><span class="sxs-lookup"><span data-stu-id="fe173-102">Configure, deploy, and run in Azure</span></span>
  description: <span data-ttu-id="fe173-103">Azure での構成、展開、実行</span><span class="sxs-lookup"><span data-stu-id="fe173-103">Configure, deploy, and run in Azure</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 0e25bfbecabeaa7e20c041d8a2e8f3bd3ca67b18
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44241682"
durationInMinutes: 12
interactive: bash
content: '[!include[](includes/6-configure-deploy-run-azure.md)]'
