### YamlMime:ModuleUnit
uid: learn.manage-secrets-with-azure-key-vault.6-configure-deploy-run-azure
title: <span data-ttu-id="09d09-101">Azure での構成、展開、実行</span><span class="sxs-lookup"><span data-stu-id="09d09-101">Configure, deploy, and run in Azure</span></span>
metadata:
  title: <span data-ttu-id="09d09-102">Azure での構成、展開、実行</span><span class="sxs-lookup"><span data-stu-id="09d09-102">Configure, deploy, and run in Azure</span></span>
  description: <span data-ttu-id="09d09-103">Azure での構成、展開、実行</span><span class="sxs-lookup"><span data-stu-id="09d09-103">Configure, deploy, and run in Azure</span></span>
  ms.openlocfilehash: 12d10497be5490db01c1822d11cd81f3145588f5
  ms.sourcegitcommit: 926510a198d738c5726081f6d7994fe9b6fc6edb
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 08/29/2018
  ms.locfileid: "43179949"
durationInMinutes: 12
interactive: bash
content: '[!include[](includes/6-configure-deploy-run-azure.md)]'
