### YamlMime:ModuleUnit
uid: learn.optimize-web-app-with-redis.3-configure-redis-cache
title: Redis Cache を構成する
metadata:
  title: Redis Cache を構成する
  description: Redis Cache を構成する
  ms.openlocfilehash: 97146e54b1e46659f765149a3199b57701933a2b
  ms.sourcegitcommit: 314b617e66d461bd6bf5aa076aacdc150b773606
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "43834250"
durationInMinutes: 5
content: '[!include[](includes/3-configure-redis-cache.md)]'
