### YamlMime:ModuleUnit
uid: learn.intro-to-containers.2-configure-local
metadata:
  title: <span data-ttu-id="18ed8-101">ローカル コンテナー開発環境の構成</span><span class="sxs-lookup"><span data-stu-id="18ed8-101">Configure a local container development environment</span></span>
  description: <span data-ttu-id="18ed8-102">ローカル コンテナー開発環境を構成します。</span><span class="sxs-lookup"><span data-stu-id="18ed8-102">Configure a local container development environment.</span></span>
  ms.openlocfilehash: f33047eb1295ea2dd44904a8e2ddb1d78b413682
  ms.sourcegitcommit: 56db32ad6f98b7d769f2b1201825d4f6d9b7362d
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43727905"
title: <span data-ttu-id="18ed8-103">ローカル コンテナー開発環境の構成</span><span class="sxs-lookup"><span data-stu-id="18ed8-103">Configure a local container development environment</span></span>
durationInMinutes: 10
content: '[!include[](includes/2-configure-local.md)]'
