### YamlMime:ModuleUnit
uid: learn.intro-to-containers.2-configure-local
metadata:
  title: ローカル コンテナー開発環境の構成
  description: ローカル コンテナー開発環境を構成します。
  displayType: one-column
  ms.openlocfilehash: 943d4a5d8cb84c7b07d1e8ae49dac8636763f797
  ms.sourcegitcommit: 16445658b8c25e5f5cbcfc7b1d8a36222f4e902c
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 08/24/2018
  ms.locfileid: "42906779"
title: ローカル コンテナー開発環境の構成
durationInMinutes: 10
content: '[!include[](includes/2-configure-local.md)]'
