### YamlMime:ModuleUnit
uid: learn.intro-to-containers.2-configure-local
metadata:
  title: ローカル コンテナー開発環境の構成
  description: ローカル コンテナー開発環境を構成します。
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 365b86322b9585abcedd1a61fdcf91840bae48bf
  ms.sourcegitcommit: b6f5aa15bae13cb0f53667fba1d404b7bec76f67
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/17/2018
  ms.locfileid: "45758627"
title: ローカル コンテナー開発環境の構成
durationInMinutes: 10
content: '[!include[](includes/2-configure-local.md)]'
