### YamlMime:ModuleUnit
uid: learn.intro-to-containers.2-configure-local
metadata:
  title: ローカル コンテナー開発環境の構成
  description: ローカル コンテナー開発環境を構成します。
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
title: ローカル コンテナー開発環境の構成
durationInMinutes: 10
content: |
  [!include[](includes/2-configure-local.md)]