### YamlMime:ModuleUnit
uid: learn.intro-to-containers.2-configure-local
metadata:
  title: <span data-ttu-id="34617-101">ローカル コンテナー開発環境の構成</span><span class="sxs-lookup"><span data-stu-id="34617-101">Configure a local container development environment</span></span>
  description: <span data-ttu-id="34617-102">ローカル コンテナー開発環境を構成します。</span><span class="sxs-lookup"><span data-stu-id="34617-102">Configure a local container development environment.</span></span>
  displayType: one-column
  ms.openlocfilehash: 943d4a5d8cb84c7b07d1e8ae49dac8636763f797
  ms.sourcegitcommit: 16445658b8c25e5f5cbcfc7b1d8a36222f4e902c
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 08/24/2018
  ms.locfileid: "42906779"
title: <span data-ttu-id="34617-103">ローカル コンテナー開発環境の構成</span><span class="sxs-lookup"><span data-stu-id="34617-103">Configure a local container development environment</span></span>
durationInMinutes: 10
content: '[!include[](includes/2-configure-local.md)]'
