### YamlMime:ModuleUnit
uid: learn.intro-to-containers.2-configure-local
metadata:
  title: <span data-ttu-id="80534-101">ローカル コンテナー開発環境の構成</span><span class="sxs-lookup"><span data-stu-id="80534-101">Configure a local container development environment</span></span>
  description: <span data-ttu-id="80534-102">ローカル コンテナー開発環境を構成します。</span><span class="sxs-lookup"><span data-stu-id="80534-102">Configure a local container development environment.</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 365b86322b9585abcedd1a61fdcf91840bae48bf
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44246720"
title: <span data-ttu-id="80534-103">ローカル コンテナー開発環境の構成</span><span class="sxs-lookup"><span data-stu-id="80534-103">Configure a local container development environment</span></span>
durationInMinutes: 10
content: '[!include[](includes/2-configure-local.md)]'
