### YamlMime:ModuleUnit
uid: learn.design-for-performance-and-scalability.5-identify-performance-bottlenecks-in-your-application
title: アプリケーションでのパフォーマンスのボトルネックを特定する
metadata:
  title: アプリケーションでのパフォーマンスのボトルネックを特定する
  description: このユニットでは、アプリケーションでのパフォーマンスのボトルネックを特定する方法について説明します
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: a01a564ec53bf55924adfb91fcf79031bc2396f7
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44240209"
durationInMinutes: 5
content: >
  [!include[](includes/5-identify-performance-bottlenecks-in-your-application.md)]
quiz:
  title: 知識チェック - アプリケーションでのパフォーマンスのボトルネックを特定する
  questions:
  - content: 次のうち、Application Insights の説明として最も適切なものはどれですか。
    choices:
    - content: Azure での監視ニーズの 1 つの窓
      isCorrect: false
      incorrectExplanation: Application Insights は、アプリケーションのパフォーマンスに関する豊富なデータを提供できる、Azure の包括的な監視ソリューションです。
    - content: 正常性エンドポイント監視パターンの実装
      isCorrect: false
      incorrectExplanation: 正常性エンドポイント監視パターンは、アプリケーションによって公開されるエンドポイントの全体的な正常性の監視に重点を置いています。
    - content: インフラストラクチャ全体およびアプリケーション間でのログの収集を可能にするワークスペース
      isCorrect: false
      incorrectExplanation: Log Analytics は、インフラストラクチャ全体およびアプリケーション間でのログの収集を可能にするワークスペースです。
    - content: Web アプリケーションの可用性、パフォーマンス、使用状況を監視するサービス
      isCorrect: true
      correctExplanation: Application Insights は、Web アプリケーションの可用性、パフォーマンス、使用状況を監視するサービスです。
  - content: カスタム ログとメトリックを追跡するために、Log Analytics を使用することができます。
    choices:
    - content: "True"
      isCorrect: true
      correctExplanation: カスタム ログおよびメトリックについては、HTTP データ コレクター API を使用して REST API クライアントから Log Analytics にデータを書き込んだり、Azure Logic Apps を使用してカスタム ワークフローからデータを書き込んだりすることもできます。
    - content: "False"
      isCorrect: false
      incorrectExplanation: カスタム ログおよびメトリックについては、HTTP データ コレクター API を使用して REST API クライアントから Log Analytics にデータを書き込んだり、Azure Logic Apps を使用してカスタム ワークフローからデータを書き込んだりすることもできます。
