### YamlMime:ModuleUnit
uid: learn.design-for-performance-and-scalability.5-identify-performance-bottlenecks-in-your-application
title: アプリケーションでのパフォーマンスのボトルネックを特定する
metadata:
  title: アプリケーションでのパフォーマンスのボトルネックを特定する
  description: このユニットでは、アプリケーションでのパフォーマンスのボトルネックを特定する方法について説明します
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: c7d8f1f8564a139f58fb17efc300af92e96cf906
  ms.sourcegitcommit: b21a4b22de591cfa776684ba2eab9ba27248c65d
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/19/2018
  ms.locfileid: "46348095"
durationInMinutes: 9
content: >
  [!include[](includes/5-identify-performance-bottlenecks-in-your-application.md)]
quiz:
  title: 自分の知識をチェックする
  questions:
  - content: 次のうち、Application Insights の説明として最も適切なものはどれですか。
    choices:
    - content: Azure でのすべての監視ニーズに対応する単一のビュー
      isCorrect: false
      incorrectExplanation: Application Insights では、アプリケーションのパフォーマンスに関する豊富なデータが提供されますが、Azure の包括的監視ソリューションとは言えません。
    - content: 正常性エンドポイント監視パターンの実装
      isCorrect: false
      incorrectExplanation: 正常性エンドポイント監視パターンは、アプリケーションによって公開されるエンドポイントの全体的な正常性の監視に重点を置いています。
    - content: インフラストラクチャ全体およびアプリケーション間でのログの収集を可能にするワークスペース
      isCorrect: false
      incorrectExplanation: Log Analytics は、インフラストラクチャ全体およびアプリケーションのログの収集を可能にするワークスペースです。
    - content: Web アプリケーションの可用性、パフォーマンス、使用状況を監視するサービス
      isCorrect: true
      correctExplanation: Application Insights は、Web アプリケーションの可用性、パフォーマンス、使用状況を監視するサービスです。
  - content: '正誤問題: Log Analytics はカスタム ログとメトリックを追跡します。'
    choices:
    - content: ○
      isCorrect: true
      correctExplanation: カスタム ログおよびメトリックについては、HTTP データ コレクター API を使用して REST API クライアントから Log Analytics にデータを書き込んだり、Azure Logic Apps を使用してカスタム ワークフローからデータを書き込んだりすることもできます。
    - content: ×
      isCorrect: false
      incorrectExplanation: カスタム ログおよびメトリックについては、HTTP データ コレクター API を使用して REST API クライアントから Log Analytics にデータを書き込んだり、Azure Logic Apps を使用してカスタム ワークフローからデータを書き込んだりすることもできます。
