### YamlMime:ModuleUnit
uid: learn.optimize-web-app-with-redis.3-configure-redis-cache
title: Redis Cache を構成する
metadata:
  title: Redis Cache を構成する
  description: Redis Cache を構成する
  ms.openlocfilehash: 97146e54b1e46659f765149a3199b57701933a2b
  ms.sourcegitcommit: bf091e3a389138b59573865ca54775e38a4ffa1f
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 08/29/2018
  ms.locfileid: "43154662"
durationInMinutes: 5
content: '[!include[](includes/3-configure-redis-cache.md)]'
