### YamlMime:ModuleUnit
uid: learn.introduction-to-security.5-network-security
title: <span data-ttu-id="2cce6-101">ネットワークを保護する</span><span class="sxs-lookup"><span data-stu-id="2cce6-101">Protect your network</span></span>
metadata:
  title: <span data-ttu-id="2cce6-102">ネットワークを保護する</span><span class="sxs-lookup"><span data-stu-id="2cce6-102">Protect your network</span></span>
  description: <span data-ttu-id="2cce6-103">このユニットでは、ネットワーク インフラストラクチャをセキュリティで保護する方法について説明します。</span><span class="sxs-lookup"><span data-stu-id="2cce6-103">In this unit, we'll discuss how to secure your network infrastructure.</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 434584c1861f5b8031069c787b878c654a8ba848
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47137126"
durationInMinutes: 5
content: '[!include[](includes/5-network-security.md)]'
