### YamlMime:ModuleUnit
uid: learn.introduction-to-security.5-network-security
title: <span data-ttu-id="f7b87-101">ネットワークを保護する</span><span class="sxs-lookup"><span data-stu-id="f7b87-101">Protect your network</span></span>
metadata:
  title: <span data-ttu-id="f7b87-102">ネットワークを保護する</span><span class="sxs-lookup"><span data-stu-id="f7b87-102">Protect your network</span></span>
  description: <span data-ttu-id="f7b87-103">このユニットでは、ネットワーク インフラストラクチャをセキュリティで保護する方法について説明します</span><span class="sxs-lookup"><span data-stu-id="f7b87-103">In this unit we'll discuss how to secure your network infrastructure</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 9e292fa70474a3250e8b53689a2bedaaf261ea96
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44246125"
durationInMinutes: 5
content: '[!include[](includes/5-network-security.md)]'
