### YamlMime:ModuleUnit
uid: learn.introduction-to-security.5-network-security
title: ネットワークを保護する
metadata:
  title: ネットワークを保護する
  description: このユニットでは、ネットワーク インフラストラクチャをセキュリティで保護する方法について説明します
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 9e292fa70474a3250e8b53689a2bedaaf261ea96
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44246125"
durationInMinutes: 5
content: '[!include[](includes/5-network-security.md)]'
