### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-web-apps.5-exercise-create-an-asp.net-core-web-application-on-linux
title: <span data-ttu-id="4fca5-101">演習 - Linux で ASP.NET Core アプリケーションを作成する</span><span class="sxs-lookup"><span data-stu-id="4fca5-101">Exercise - Create an ASP.NET Core application on Linux</span></span>
metadata:
  title: <span data-ttu-id="4fca5-102">演習 - Linux で ASP.NET Core アプリケーションを作成する</span><span class="sxs-lookup"><span data-stu-id="4fca5-102">Exercise - Create an ASP.NET Core application on Linux</span></span>
  description: <span data-ttu-id="4fca5-103">演習 - Linux で ASP.NET Core アプリケーションを作成する</span><span class="sxs-lookup"><span data-stu-id="4fca5-103">Exercise - Create an ASP.NET Core application on Linux</span></span>
  ms.openlocfilehash: 1205619f0129555a08587fa142627e6d917e3fcb
  ms.sourcegitcommit: a8497a897faccb27bfeaf5812a5887ac15f97625
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 08/24/2018
  ms.locfileid: "42820485"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]'
