### YamlMime:ModuleUnit
uid: learn.interactive-deep-learning.4-configure-dsvm
title: DSVM を構成する
metadata:
  title: ディープ ラーニング用に Data Science Virtual Machine を構成する
  description: ディープ ラーニング用に Data Science Virtual Machine を構成する
  ms.openlocfilehash: 54f188e18c055a9d80f3a71bf482a781b723b1e2
  ms.sourcegitcommit: 314b617e66d461bd6bf5aa076aacdc150b773606
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "43833170"
interactive: bash
durationInMinutes: 30
content: '[!include[](includes/4-configure-dsvm.md)]'
