### YamlMime:ModuleUnit
uid: learn.interactive-deep-learning.4-configure-dsvm
title: DSVM を構成する
metadata:
  title: ディープ ラーニング用に Data Science Virtual Machine を構成する
  description: ディープ ラーニング用に Data Science Virtual Machine を構成する
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
labId: 45998
interactive: bash
azureSandbox: true
durationInMinutes: 30
content: |
  [!include[](includes/4-configure-dsvm.md)]