### YamlMime:ModuleUnit
uid: learn.interactive-deep-learning.4-configure-dsvm
title: <span data-ttu-id="58aaf-101">DSVM を構成する</span><span class="sxs-lookup"><span data-stu-id="58aaf-101">Configure DSVM</span></span>
metadata:
  title: <span data-ttu-id="58aaf-102">ディープ ラーニング用に Data Science Virtual Machine を構成する</span><span class="sxs-lookup"><span data-stu-id="58aaf-102">Configure the Data Science Virtual Machine for Deep Learning</span></span>
  description: <span data-ttu-id="58aaf-103">ディープ ラーニング用に Data Science Virtual Machine を構成する</span><span class="sxs-lookup"><span data-stu-id="58aaf-103">Configure the Data Science Virtual Machine for Deep Learning</span></span>
  ms.openlocfilehash: 54f188e18c055a9d80f3a71bf482a781b723b1e2
  ms.sourcegitcommit: 314b617e66d461bd6bf5aa076aacdc150b773606
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "43833170"
interactive: bash
durationInMinutes: 30
content: '[!include[](includes/4-configure-dsvm.md)]'
