### YamlMime:ModuleUnit
uid: learn.interactive-deep-learning.4-configure-dsvm
title: <span data-ttu-id="e17cb-101">DSVM を構成する</span><span class="sxs-lookup"><span data-stu-id="e17cb-101">Configure DSVM</span></span>
metadata:
  title: <span data-ttu-id="e17cb-102">ディープ ラーニング用に Data Science Virtual Machine を構成する</span><span class="sxs-lookup"><span data-stu-id="e17cb-102">Configure the Data Science Virtual Machine for Deep Learning</span></span>
  description: <span data-ttu-id="e17cb-103">ディープ ラーニング用に Data Science Virtual Machine を構成する</span><span class="sxs-lookup"><span data-stu-id="e17cb-103">Configure the Data Science Virtual Machine for Deep Learning</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: e7beee6bf1a56df0378cba82b042d506589f361d
  ms.sourcegitcommit: 8213d1af6ad9da967a5e195f0b40b00265cb192c
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/10/2018
  ms.locfileid: "44309339"
interactive: bash
azureSandbox: true
durationInMinutes: 30
content: '[!include[](includes/4-configure-dsvm.md)]'
