### YamlMime:ModuleUnit
uid: learn.optimize-web-app-with-redis.3-configure-redis-cache
title: <span data-ttu-id="d65ea-101">Redis Cache を構成する</span><span class="sxs-lookup"><span data-stu-id="d65ea-101">Configure Redis cache</span></span>
metadata:
  title: <span data-ttu-id="d65ea-102">Redis Cache を構成する</span><span class="sxs-lookup"><span data-stu-id="d65ea-102">Configure Redis cache</span></span>
  description: <span data-ttu-id="d65ea-103">Redis Cache を構成する</span><span class="sxs-lookup"><span data-stu-id="d65ea-103">Configure Redis cache</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: cf34eb91055b1a3f200c204af82bc93cb86e156f
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44237955"
durationInMinutes: 5
content: '[!include[](includes/3-configure-redis-cache.md)]'
