### YamlMime:ModuleUnit
uid: learn.run-docker-containers-aci.4-use-environment-variables
metadata:
  title: 環境変数を設定する
  description: Azure Container Instances で環境変数を設定します。
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
title: 環境変数を設定する
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: |
  [!include[](includes/4-use-environment-variables.md)]