### YamlMime:ModuleUnit
uid: learn.run-docker-containers-aci.4-use-environment-variables
metadata:
  title: 環境変数の設定
  description: Azure Container Instances で環境変数を設定します。
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 121d22c224c33875cf10038d9c63596882a3b1f4
  ms.sourcegitcommit: 8a009788ee73c5d7caa6cd4f1105260c5cc9b846
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/22/2018
  ms.locfileid: "46570598"
title: 環境変数の設定
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/4-use-environment-variables.md)]'
