### YamlMime:ModuleUnit
uid: learn.secure-your-azure-virtual-machine-disks.5-automate-secure-vm-deployments-using-arm-templates
title: Azure Resource Manager テンプレートを暗号化してセキュリティで保護された VM のデプロイを自動化します。
metadata:
  title: Azure Resource Manager テンプレートを暗号化してセキュリティで保護された VM のデプロイを自動化します。
  description: Azure Resource Manager テンプレートを暗号化してセキュリティで保護された VM のデプロイを自動化します。
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 5
content: |
  [!include[](includes/5-automate-secure-vm-deployments-using-arm-templates.md)]