### YamlMime:ModuleUnit
uid: learn.design-for-security.6-network-security
title: <span data-ttu-id="526da-101">ネットワークのセキュリティ</span><span class="sxs-lookup"><span data-stu-id="526da-101">Network security</span></span>
metadata:
  title: <span data-ttu-id="526da-102">ネットワークのセキュリティ</span><span class="sxs-lookup"><span data-stu-id="526da-102">Network security</span></span>
  description: <span data-ttu-id="526da-103">このユニットでは、ネットワーク インフラストラクチャをセキュリティで保護する方法について説明します。</span><span class="sxs-lookup"><span data-stu-id="526da-103">In this unit we'll discuss how to secure your network infrastructure</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 90be1e461ce19e0bd7a18e869397db2d0ab3abfa
  ms.sourcegitcommit: f9023fdf01347b57619974b6961e1565cfc483d9
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44240755"
durationInMinutes: 5
content: >
  [!include[](includes/6-network-security.md)]
quiz:
  title: <span data-ttu-id="526da-104">知識チェック - ネットワーク セキュリティ</span><span class="sxs-lookup"><span data-stu-id="526da-104">Knowledge Check - Network security</span></span>
  questions:
  - content: <span data-ttu-id="526da-105">Azure Nsg を使用した場合、次のどの通信をセキュリティで保護できますか?</span><span class="sxs-lookup"><span data-stu-id="526da-105">Azure NSGs can be used to secure communication between which of the following?</span></span>
    choices:
    - content: <span data-ttu-id="526da-106">仮想マシンとインターネット間の通信</span><span class="sxs-lookup"><span data-stu-id="526da-106">Communication between virtual machines and the internet</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="526da-107">NSG を使用すると、この通信フローをセキュリティで保護できますが、これが唯一正しい選択肢ではありません。</span><span class="sxs-lookup"><span data-stu-id="526da-107">NSGs can be used to secure this communication flow, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="526da-108">VNet 内の仮想マシン間の通信</span><span class="sxs-lookup"><span data-stu-id="526da-108">Communication between virtual machines within a VNet</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="526da-109">NSG を使用すると、この通信フローをセキュリティで保護できますが、これが唯一正しい選択肢ではありません。</span><span class="sxs-lookup"><span data-stu-id="526da-109">NSGs can be used to secure this communication flow, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="526da-110">オンプレミス ネットワーク内のシステムとの通信</span><span class="sxs-lookup"><span data-stu-id="526da-110">Communication with systems in an on-premises network</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="526da-111">NSG を使用すると、この通信フローをセキュリティで保護できますが、これが唯一正しい選択肢ではありません。</span><span class="sxs-lookup"><span data-stu-id="526da-111">NSGs can be used to secure this communication flow, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="526da-112">上記のすべて</span><span class="sxs-lookup"><span data-stu-id="526da-112">All of the above</span></span>
      isCorrect: true
      correctExplanation: <span data-ttu-id="526da-113">NSG を使用すると、上記のすべての通信フローのセキュリティを保護することができます。</span><span class="sxs-lookup"><span data-stu-id="526da-113">NSGs can be used to secure all of the above communication flows.</span></span>
  - content: <span data-ttu-id="526da-114">次のうち、インターネットに接続されているサービスをネットワーク攻撃から保護する方法でないのはどれですか?</span><span class="sxs-lookup"><span data-stu-id="526da-114">Which of the following is not a method of protecting internet facing services from network attacks?</span></span>
    choices:
    - content: <span data-ttu-id="526da-115">Azure DDoS</span><span class="sxs-lookup"><span data-stu-id="526da-115">Azure DDoS</span></span>
      isCorrect: false
      incorrectExplanation: '<span data-ttu-id="526da-116">Azure DDoS を使用すると、インターネットに接続されているサービスを DoS 攻撃から保護できます。</span><span class="sxs-lookup"><span data-stu-id="526da-116">Azure DDoS can be used to protect your internet facing services from a DoS attack.</span></span> '
    - content: <span data-ttu-id="526da-117">Azure Application Gateway WAF</span><span class="sxs-lookup"><span data-stu-id="526da-117">Azure Application Gateway WAF</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="526da-118">Application Gateway の WAF を使用すると、インターネットに接続されているサービスを XSS や SQL インジェクションなどの攻撃から保護できます。</span><span class="sxs-lookup"><span data-stu-id="526da-118">Application Gateway WAF can be used to protect your internet facing services from attacks such as XSS and SQL injection.</span></span>
    - content: <span data-ttu-id="526da-119">Azure Disk Encryption</span><span class="sxs-lookup"><span data-stu-id="526da-119">Azure Disk Encryption</span></span>
      isCorrect: true
      correctExplanation: <span data-ttu-id="526da-120">Azure Disk Encryption は、仮想マシンの VHD の露出を保護しますが、ネットワーク経由の攻撃からは保護しません。</span><span class="sxs-lookup"><span data-stu-id="526da-120">Azure Disk Encryption protects your virtual machine VHDs from exposure, but does not provide protection from network based attacks.</span></span>
    - content: <span data-ttu-id="526da-121">ネットワーク仮想アプライアンス</span><span class="sxs-lookup"><span data-stu-id="526da-121">A network virtual appliance</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="526da-122">ネットワーク仮想アプライアンスは、インターネットに接続されているリソースをネットワークをカスタマイズして保護できます。</span><span class="sxs-lookup"><span data-stu-id="526da-122">Network virtual appliances can provide customized network protection for your internet facing resources.</span></span>
