### YamlMime:ModuleUnit
uid: learn.design-for-security.6-network-security
title: <span data-ttu-id="7a414-101">ネットワークのセキュリティ</span><span class="sxs-lookup"><span data-stu-id="7a414-101">Network security</span></span>
metadata:
  title: <span data-ttu-id="7a414-102">ネットワークのセキュリティ</span><span class="sxs-lookup"><span data-stu-id="7a414-102">Network security</span></span>
  description: <span data-ttu-id="7a414-103">このユニットでは、ネットワーク インフラストラクチャをセキュリティで保護する方法について説明します</span><span class="sxs-lookup"><span data-stu-id="7a414-103">In this unit we'll discuss how to secure your network infrastructure</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: cc35a096e064136f7d56fc05c4ce856fd1918641
  ms.sourcegitcommit: b21a4b22de591cfa776684ba2eab9ba27248c65d
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/19/2018
  ms.locfileid: "46350920"
durationInMinutes: 10
content: >
  [!include[](includes/6-network-security.md)]
quiz:
  title: <span data-ttu-id="7a414-104">自分の知識をチェックする</span><span class="sxs-lookup"><span data-stu-id="7a414-104">Check your knowledge</span></span>
  questions:
  - content: <span data-ttu-id="7a414-105">Azure ネットワーク セキュリティ グループを使用した場合、次のどの通信をセキュリティで保護できますか?</span><span class="sxs-lookup"><span data-stu-id="7a414-105">Azure network security group can be used to secure communication between which of the following?</span></span>
    choices:
    - content: <span data-ttu-id="7a414-106">仮想マシンとインターネット</span><span class="sxs-lookup"><span data-stu-id="7a414-106">Virtual machines and the internet</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7a414-107">ネットワーク セキュリティ グループは完全カスタマイズが可能であり、仮想マシンとやりとりされるネットワーク通信を完全にロックダウンできます。</span><span class="sxs-lookup"><span data-stu-id="7a414-107">Network security groups are fully customizable, and give you the ability to fully lock down network communication to and from your virtual machines.</span></span>
    - content: <span data-ttu-id="7a414-108">VNet 内の仮想マシン</span><span class="sxs-lookup"><span data-stu-id="7a414-108">Virtual machines within a VNet</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7a414-109">ネットワーク セキュリティ グループは完全カスタマイズが可能であり、仮想マシンとやりとりされるネットワーク通信を完全にロックダウンできます。</span><span class="sxs-lookup"><span data-stu-id="7a414-109">Network security groups are fully customizable, and give you the ability to fully lock down network communication to and from your virtual machines.</span></span>
    - content: <span data-ttu-id="7a414-110">オンプレミス ネットワークのシステム</span><span class="sxs-lookup"><span data-stu-id="7a414-110">Systems in an on-premises network</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7a414-111">ネットワーク セキュリティ グループは完全カスタマイズが可能であり、仮想マシンとやりとりされるネットワーク通信を完全にロックダウンできます。</span><span class="sxs-lookup"><span data-stu-id="7a414-111">Network security groups are fully customizable, and give you the ability to fully lock down network communication to and from your virtual machines.</span></span>
    - content: <span data-ttu-id="7a414-112">上記のすべて</span><span class="sxs-lookup"><span data-stu-id="7a414-112">All of the above</span></span>
      isCorrect: true
      correctExplanation: <span data-ttu-id="7a414-113">ネットワーク セキュリティ グループは完全カスタマイズが可能であり、仮想マシンとやりとりされるネットワーク通信を完全にロックダウンできます。</span><span class="sxs-lookup"><span data-stu-id="7a414-113">Network security groups are fully customizable, and give you the ability to fully lock down network communication to and from your virtual machines.</span></span>
  - content: <span data-ttu-id="7a414-114">次のうち、インターネットに接続されているサービスをネットワーク攻撃から保護する方法でないのはどれですか?</span><span class="sxs-lookup"><span data-stu-id="7a414-114">Which of the following is not a method for protecting internet facing services from network attacks?</span></span>
    choices:
    - content: <span data-ttu-id="7a414-115">Azure DDoS</span><span class="sxs-lookup"><span data-stu-id="7a414-115">Azure DDoS</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7a414-116">Azure Disk Encryption は、仮想マシンの仮想ハード ディスクの露出を防ぎますが、ネットワーク経由の攻撃の防御にはなりません。</span><span class="sxs-lookup"><span data-stu-id="7a414-116">Azure Disk Encryption protects your virtual machine virtual hard disks from exposure, but does not provide protection from network based attacks.</span></span>
    - content: <span data-ttu-id="7a414-117">Azure Application Gateway WAF</span><span class="sxs-lookup"><span data-stu-id="7a414-117">Azure Application Gateway WAF</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7a414-118">Azure Disk Encryption は、仮想マシンの仮想ハード ディスクの露出を防ぎますが、ネットワーク経由の攻撃の防御にはなりません。</span><span class="sxs-lookup"><span data-stu-id="7a414-118">Azure Disk Encryption protects your virtual machine virtual hard disks from exposure, but does not provide protection from network based attacks.</span></span>
    - content: <span data-ttu-id="7a414-119">Azure Disk Encryption</span><span class="sxs-lookup"><span data-stu-id="7a414-119">Azure Disk Encryption</span></span>
      isCorrect: true
      correctExplanation: <span data-ttu-id="7a414-120">Azure Disk Encryption は、仮想マシンの仮想ハード ディスクの露出を防ぎますが、ネットワーク経由の攻撃の防御にはなりません。</span><span class="sxs-lookup"><span data-stu-id="7a414-120">Azure Disk Encryption protects your virtual machine virtual hard disks from exposure, but does not provide protection from network based attacks.</span></span>
    - content: <span data-ttu-id="7a414-121">ネットワーク仮想アプライアンス</span><span class="sxs-lookup"><span data-stu-id="7a414-121">A network virtual appliance</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="7a414-122">Azure Disk Encryption は、仮想マシンの仮想ハード ディスクの露出を防ぎますが、ネットワーク経由の攻撃の防御にはなりません。</span><span class="sxs-lookup"><span data-stu-id="7a414-122">Azure Disk Encryption protects your virtual machine virtual hard disks from exposure, but does not provide protection from network based attacks.</span></span>
