### YamlMime:ModuleUnit
uid: learn.store-app-data-with-azure-blob-storage.5-configure-and-initialize-the-client-library
title: <span data-ttu-id="0a3fa-101">クライアント ライブラリを構成して初期化する</span><span class="sxs-lookup"><span data-stu-id="0a3fa-101">Configure and initialize the client library</span></span>
metadata:
  title: <span data-ttu-id="0a3fa-102">クライアント ライブラリを構成して初期化する</span><span class="sxs-lookup"><span data-stu-id="0a3fa-102">Configure and initialize the client library</span></span>
  description: <span data-ttu-id="0a3fa-103">クライアント ライブラリを構成して初期化する</span><span class="sxs-lookup"><span data-stu-id="0a3fa-103">Configure and initialize the client library</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: bedd297c48ead2c2aadba57e57e3bb8b965344fb
  ms.sourcegitcommit: b21a4b22de591cfa776684ba2eab9ba27248c65d
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/19/2018
  ms.locfileid: "46352729"
durationInMinutes: 10
interactive: bash-editor
azureSandbox: true
content: '[!include[](includes/5-configure-and-initialize-the-client-library.md)]'
