### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.1-create-azure-iot-central-application
title: Azure IoT Central アプリケーションを作成する
metadata:
  title: Azure IoT Central アプリケーションを作成する
  description: Azure IoT Central アプリケーションを作成する
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 5
content: |
  [!include[](includes/1-create-azure-iot-central-application.md)]