### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.1-create-azure-iot-central-application
title: <span data-ttu-id="15d0d-101">Azure IoT Central アプリケーションを作成する</span><span class="sxs-lookup"><span data-stu-id="15d0d-101">Create an Azure IoT Central application</span></span>
metadata:
  title: <span data-ttu-id="15d0d-102">Azure IoT Central アプリケーションを作成する</span><span class="sxs-lookup"><span data-stu-id="15d0d-102">Create an Azure IoT Central application</span></span>
  description: <span data-ttu-id="15d0d-103">Azure IoT Central アプリケーションを作成する</span><span class="sxs-lookup"><span data-stu-id="15d0d-103">Create an Azure IoT Central application</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 98e9a83d594bc3611f3048909b7d238ea289901e
  ms.sourcegitcommit: 46c8d35790efaafa6a4637f7688482e3a754d7f3
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44256522"
durationInMinutes: 5
content: '[!include[](includes/1-create-azure-iot-central-application.md)]'
