### YamlMime:ModuleUnit
uid: learn.monitor-manage-device-with-iotcentral.3-connect-your-application-to-simulator
title: シミュレートしたコーヒー マシンをアプリケーションに接続する
metadata:
  title: シミュレートしたコーヒー マシンをアプリケーションに接続する
  description: シミュレートしたコーヒー マシンをアプリケーションに接続する
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 5e1c175df222a53ef2cd352fbd12feceabe25fad
  ms.sourcegitcommit: 46c8d35790efaafa6a4637f7688482e3a754d7f3
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/09/2018
  ms.locfileid: "44256641"
durationInMinutes: 5
content: '[!include[](includes/3-connect-your-application-to-simulator.md)]'
