### YamlMime:ModuleUnit
uid: learn.enable-reliable-messaging-for-big-data-applications-using-azure-event-hubs.5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub
title: 演習 - イベント ハブを経由してメッセージを送受信するアプリケーションを構成する
metadata:
  title: 演習 - イベント ハブを経由してメッセージを送受信するアプリケーションを構成する
  description: 演習 - イベント ハブを経由してメッセージを送受信するアプリケーションを構成する
  ms.openlocfilehash: 07be67eb4f06fa18e8587ac769436ef497037baf
  ms.sourcegitcommit: 1131013f5b019c82e7d004cdcdb8184fca1c66ed
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 08/24/2018
  ms.locfileid: "42924352"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-configure-applications-to-send-or-receive-messages-through-an-event-hub.md)]'
