### YamlMime:ModuleUnit
uid: learn.make-your-virtual-machines-highly-available.5-configure-a-load-balancer-in-azure
title: <span data-ttu-id="dc0d1-101">Azure でロード バランサーを構成する</span><span class="sxs-lookup"><span data-stu-id="dc0d1-101">Configure a load balancer in Azure</span></span>
metadata:
  title: <span data-ttu-id="dc0d1-102">Azure でロード バランサーを構成する</span><span class="sxs-lookup"><span data-stu-id="dc0d1-102">Configure a load balancer in Azure</span></span>
  description: <span data-ttu-id="dc0d1-103">Azure でロード バランサーを構成する</span><span class="sxs-lookup"><span data-stu-id="dc0d1-103">Configure a load balancer in Azure</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: f0ac81ae3551f12da7b649c77332c92b51ba3089
  ms.sourcegitcommit: c02f803ad02769c7185b7f20e04d64fee38d9931
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/25/2018
  ms.locfileid: "47137856"
durationInMinutes: 5
content: '[!include[](includes/5-configure-a-load-balancer-in-azure.md)]'
