### YamlMime:ModuleUnit
uid: learn.make-your-virtual-machines-highly-available.5-exercise-configure-a-load-balancer-in-azure
title: <span data-ttu-id="738d5-101">演習 - Azure でロード バランサーを構成する</span><span class="sxs-lookup"><span data-stu-id="738d5-101">Exercise - Configure a load balancer in Azure</span></span>
metadata:
  title: <span data-ttu-id="738d5-102">演習 - Azure でロード バランサーを構成する</span><span class="sxs-lookup"><span data-stu-id="738d5-102">Exercise - Configure a load balancer in Azure</span></span>
  description: <span data-ttu-id="738d5-103">演習 - Azure でロード バランサーを構成する</span><span class="sxs-lookup"><span data-stu-id="738d5-103">Exercise - Configure a load balancer in Azure</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: d5a6025caf153c009f67ea0da8184d39e96e9966
  ms.sourcegitcommit: e1fed99e287d0b8c4e6d1297bcce949ce7c8a802
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/12/2018
  ms.locfileid: "44701251"
durationInMinutes: 20
content: '[!include[](includes/5-exercise-configure-a-load-balancer-in-azure.md)]'
