### YamlMime:ModuleUnit
uid: learn.make-your-virtual-machines-highly-available.6-exercise-configure-a-load-balancer-in-azure
title: <span data-ttu-id="29a14-101">演習 - Azure でロード バランサーを構成する</span><span class="sxs-lookup"><span data-stu-id="29a14-101">Exercise - Configure a load balancer in Azure</span></span>
metadata:
  title: <span data-ttu-id="29a14-102">演習 - Azure でロード バランサーを構成する</span><span class="sxs-lookup"><span data-stu-id="29a14-102">Exercise - Configure a load balancer in Azure</span></span>
  description: <span data-ttu-id="29a14-103">演習 - Azure でロード バランサーを構成する</span><span class="sxs-lookup"><span data-stu-id="29a14-103">Exercise - Configure a load balancer in Azure</span></span>
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: d653a821bf0b0522ca085de5af23f830e6d24041
  ms.sourcegitcommit: 58e9d7fbb111af9b27ed819e4b79ba4a4e6e8a9c
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/21/2018
  ms.locfileid: "46513191"
azureSandbox: true
durationInMinutes: 15
content: '[!include[](includes/6-exercise-configure-a-load-balancer-in-azure.md)]'
