### YamlMime:ModuleUnit
uid: learn.design-a-great-azure-architecture.3-design-for-security
title: <span data-ttu-id="1e358-101">セキュリティ向けの設計</span><span class="sxs-lookup"><span data-stu-id="1e358-101">Design for security</span></span>
metadata:
  title: <span data-ttu-id="1e358-102">セキュリティ向けの設計</span><span class="sxs-lookup"><span data-stu-id="1e358-102">Design for security</span></span>
  description: <span data-ttu-id="1e358-103">セキュリティ向けの設計</span><span class="sxs-lookup"><span data-stu-id="1e358-103">Design for security</span></span>
  ms.openlocfilehash: 394af78966bfde3b2c82e2af17a10bb8680fc659
  ms.sourcegitcommit: 09425147d998035edf9d2d36006a54d85e3cf75d
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "43847250"
durationInMinutes: 10
content: >
  [!include[](includes/3-design-for-security.md)]
quiz:
  title: <span data-ttu-id="1e358-104">知識チェック - セキュリティのための設計</span><span class="sxs-lookup"><span data-stu-id="1e358-104">Knowledge check - Design for security</span></span>
  questions:
  - content: <span data-ttu-id="1e358-105">セキュリティ保護が必要な場合があるのは、次のどの種類のデータですか?</span><span class="sxs-lookup"><span data-stu-id="1e358-105">Which of the following types of data may need to have security protections?</span></span>
    choices:
    - content: <span data-ttu-id="1e358-106">個人情報を含む顧客データ</span><span class="sxs-lookup"><span data-stu-id="1e358-106">Customer data that contains personal information</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="1e358-107">このデータの適切なセキュリティ保護を提供することは重要ですが、これだけが正解ではありません。</span><span class="sxs-lookup"><span data-stu-id="1e358-107">It is important to provide proper security protections for this data, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="1e358-108">事業運営を支える財務データ</span><span class="sxs-lookup"><span data-stu-id="1e358-108">Financial data supporting business operations</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="1e358-109">このデータの適切なセキュリティ保護を提供することは重要ですが、これだけが正解ではありません。</span><span class="sxs-lookup"><span data-stu-id="1e358-109">It is important to provide proper security protections for this data, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="1e358-110">知的財産を含むデータ</span><span class="sxs-lookup"><span data-stu-id="1e358-110">Data containing intellectual property</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="1e358-111">このデータの適切なセキュリティ保護を提供することは重要ですが、これだけが正解ではありません。</span><span class="sxs-lookup"><span data-stu-id="1e358-111">It is important to provide proper security protections for this data, but this is not the only correct choice.</span></span>
    - content: <span data-ttu-id="1e358-112">上記のすべてにセキュリティ保護が必要な場合があります</span><span class="sxs-lookup"><span data-stu-id="1e358-112">All of the above may need security protections</span></span>
      isCorrect: true
      correctExplanation: <span data-ttu-id="1e358-113">上記のすべてが、追加のセキュリティ保護の恩恵を受ける場合があります。</span><span class="sxs-lookup"><span data-stu-id="1e358-113">All of the above may merit additional security protections.</span></span>
  - content: <span data-ttu-id="1e358-114">次のうち、境界層で発生する可能性がある攻撃の例はどれですか?</span><span class="sxs-lookup"><span data-stu-id="1e358-114">Which of the following is an example of an attack you might see at the perimeter layer?</span></span>
    choices:
    - content: <span data-ttu-id="1e358-115">漏洩した資格情報のインターネットへの投稿</span><span class="sxs-lookup"><span data-stu-id="1e358-115">Exposed credentials posted online</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="1e358-116">資格情報の漏洩は組織にとって巨大なリスクですが、境界層の攻撃ではありません。</span><span class="sxs-lookup"><span data-stu-id="1e358-116">Exposed credentials are a huge risk to an organization, but are not a permiter attack.</span></span>
    - content: <span data-ttu-id="1e358-117">SYN フラッド攻撃</span><span class="sxs-lookup"><span data-stu-id="1e358-117">A SYN flood attack</span></span>
      isCorrect: true
      correctExplanation: <span data-ttu-id="1e358-118">SYN フラッド攻撃は、一般的にネットワーク境界で発生するサービス拒否攻撃の一種です。</span><span class="sxs-lookup"><span data-stu-id="1e358-118">SYN flood attacks are a type of denial-of-service attack that are commonly seen on the network perimeter.</span></span>
    - content: <span data-ttu-id="1e358-119">データセンターへのドア ドラフティング</span><span class="sxs-lookup"><span data-stu-id="1e358-119">Door drafting to get into a datacenter</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="1e358-120">ドア ドラフティングは物理層の攻撃です。</span><span class="sxs-lookup"><span data-stu-id="1e358-120">Door drafting is a physical layer attack.</span></span>
    - content: <span data-ttu-id="1e358-121">仮想マシンのディスクを暗号化するランサムウェア</span><span class="sxs-lookup"><span data-stu-id="1e358-121">Ransomware that encrypts the disks of a virtual machine</span></span>
      isCorrect: false
      incorrectExplanation: <span data-ttu-id="1e358-122">ランサムウェア攻撃は VM/コンピューティング層の攻撃です。</span><span class="sxs-lookup"><span data-stu-id="1e358-122">Ransomware attacks are a VM/compute layer attack.</span></span>
