### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-web-apps.5-exercise-create-an-asp.net-core-web-application-on-linux
title: 演習 - Linux で ASP.NET Core アプリケーションを作成する
metadata:
  title: 演習 - Linux で ASP.NET Core アプリケーションを作成する
  description: 演習 - Linux で ASP.NET Core アプリケーションを作成する
  ms.openlocfilehash: 1205619f0129555a08587fa142627e6d917e3fcb
  ms.sourcegitcommit: 314b617e66d461bd6bf5aa076aacdc150b773606
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "43833223"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]'
