### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-web-apps.5-exercise-create-an-asp.net-core-web-application-on-linux
title: <span data-ttu-id="b7535-101">演習 - Linux で ASP.NET Core アプリケーションを作成する</span><span class="sxs-lookup"><span data-stu-id="b7535-101">Exercise - Create an ASP.NET Core application on Linux</span></span>
metadata:
  title: <span data-ttu-id="b7535-102">演習 - Linux で ASP.NET Core アプリケーションを作成する</span><span class="sxs-lookup"><span data-stu-id="b7535-102">Exercise - Create an ASP.NET Core application on Linux</span></span>
  description: <span data-ttu-id="b7535-103">演習 - Linux で ASP.NET Core アプリケーションを作成する</span><span class="sxs-lookup"><span data-stu-id="b7535-103">Exercise - Create an ASP.NET Core application on Linux</span></span>
  ms.openlocfilehash: 1205619f0129555a08587fa142627e6d917e3fcb
  ms.sourcegitcommit: 314b617e66d461bd6bf5aa076aacdc150b773606
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/06/2018
  ms.locfileid: "43833223"
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]'
