### YamlMime:ModuleUnit
uid: learn.run-docker-containers-aci.4-use-environment-variables
interactive: bash
metadata:
  title: <span data-ttu-id="80280-101">環境変数の設定</span><span class="sxs-lookup"><span data-stu-id="80280-101">Set environment variables</span></span>
  description: <span data-ttu-id="80280-102">Azure Container Instances で環境変数を設定します。</span><span class="sxs-lookup"><span data-stu-id="80280-102">Set environment variables in Azure Container Instances.</span></span>
  ms.openlocfilehash: 921168a568e52b47ff347521fff4969213d0fa88
  ms.sourcegitcommit: 56db32ad6f98b7d769f2b1201825d4f6d9b7362d
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43727412"
title: <span data-ttu-id="80280-103">環境変数の設定</span><span class="sxs-lookup"><span data-stu-id="80280-103">Set environment variables</span></span>
durationInMinutes: 10
content: '[!include[](includes/4-use-environment-variables.md)]'
