### YamlMime:ModuleUnit
uid: learn.run-docker-containers-aci.4-use-environment-variables
interactive: bash
metadata:
  title: 環境変数の設定
  description: Azure Container Instances で環境変数を設定します。
  ms.openlocfilehash: 921168a568e52b47ff347521fff4969213d0fa88
  ms.sourcegitcommit: 56db32ad6f98b7d769f2b1201825d4f6d9b7362d
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/05/2018
  ms.locfileid: "43727412"
title: 環境変数の設定
durationInMinutes: 10
content: '[!include[](includes/4-use-environment-variables.md)]'
