### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-web-apps.5-exercise-create-an-asp.net-core-web-application-on-linux
title: 演習 - Linux で ASP.NET Core アプリケーションを作成する
metadata:
  title: 演習 - Linux で ASP.NET Core アプリケーションを作成する
  description: 演習 - Linux で ASP.NET Core アプリケーションを作成する
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
  ms.openlocfilehash: 1755b3e9fde0c7c3e4f812551960035a76f23c88
  ms.sourcegitcommit: b21a4b22de591cfa776684ba2eab9ba27248c65d
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 09/19/2018
  ms.locfileid: "46352129"
interactive: bash
azureSandbox: true
durationInMinutes: 10
content: '[!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]'
