### YamlMime:ModuleUnit
uid: learn.host-a-web-application-with-azure-app-service.5-exercise-create-an-asp.net-core-web-application-on-linux
title: 演習 - Linux で ASP.NET Core アプリケーションを作成する
metadata:
  title: 演習 - Linux で ASP.NET Core アプリケーションを作成する
  description: 演習 - Linux で ASP.NET Core アプリケーションを作成する
  ms.date: 09/24/2018
  author: markjulmar
  ms.author: smmark
  ms.topic: interactive-tutorial
  ms.prod: learning-azure
durationInMinutes: 10
content: |
  [!include[](includes/5-exercise-create-an-asp.net-core-web-application-on-linux.md)]