### YamlMime:ModuleUnit
uid: learn.design-for-security.6-network-security
title: <span data-ttu-id="5b8c1-101">ネットワークのセキュリティ</span><span class="sxs-lookup"><span data-stu-id="5b8c1-101">Network security</span></span>
metadata:
  title: <span data-ttu-id="5b8c1-102">ネットワークのセキュリティ</span><span class="sxs-lookup"><span data-stu-id="5b8c1-102">Network security</span></span>
  description: <span data-ttu-id="5b8c1-103">このユニットでは、ネットワーク インフラストラクチャをセキュリティで保護する方法について説明します。</span><span class="sxs-lookup"><span data-stu-id="5b8c1-103">In this unit we'll discuss how to secure your network infrastructure</span></span>
  ms.openlocfilehash: f98e9f24b46119fda8be58fb4a06f8f15d60ed66
  ms.sourcegitcommit: 1663afb13d55c1fce5f2dc4c0f78ef2d74902c33
  ms.translationtype: HT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 08/31/2018
  ms.locfileid: "43366745"
durationInMinutes: 5
content: >
  [!include[](includes/6-network-security.md)]
quiz:
  title: <span data-ttu-id="5b8c1-104">知識チェック - ネットワーク セキュリティ</span><span class="sxs-lookup"><span data-stu-id="5b8c1-104">Knowledge Check - Network security</span></span>
  questions:
  - content: <span data-ttu-id="5b8c1-105">Azure App Service で Web アプリケーションを実行する場合、アプリケーションはセキュリティで完全に保護されており、その他のセキュリティ保護を行う必要はありません。</span><span class="sxs-lookup"><span data-stu-id="5b8c1-105">When running web applications on Azure App Service, your application is fully secure and you do not need to provide additional security protections.</span></span>
    choices:
    - content: <span data-ttu-id="5b8c1-106">True</span><span class="sxs-lookup"><span data-stu-id="5b8c1-106">True</span></span>
      isCorrect: false
    - content: <span data-ttu-id="5b8c1-107">False</span><span class="sxs-lookup"><span data-stu-id="5b8c1-107">False</span></span>
      isCorrect: true
  - content: <span data-ttu-id="5b8c1-108">次のうち、インターネットに接続されているサービスをネットワーク攻撃から保護する方法でないのはどれですか?</span><span class="sxs-lookup"><span data-stu-id="5b8c1-108">Which of the following is not a method of protecting internet facing services from network attacks?</span></span>
    choices:
    - content: <span data-ttu-id="5b8c1-109">Azure DDoS</span><span class="sxs-lookup"><span data-stu-id="5b8c1-109">Azure DDoS</span></span>
      isCorrect: false
    - content: <span data-ttu-id="5b8c1-110">Azure Application Gateway WAF</span><span class="sxs-lookup"><span data-stu-id="5b8c1-110">Azure Application Gateway WAF</span></span>
      isCorrect: false
    - content: <span data-ttu-id="5b8c1-111">Azure Disk Encryption</span><span class="sxs-lookup"><span data-stu-id="5b8c1-111">Azure Disk Encryption</span></span>
      isCorrect: true
    - content: <span data-ttu-id="5b8c1-112">ネットワーク仮想アプライアンス</span><span class="sxs-lookup"><span data-stu-id="5b8c1-112">A network virtual appliance</span></span>
      isCorrect: false
